# Lightning Round - Basic Features and Commands 


In this notebook, we go through basic constructs and commands.

## Competences 

The user should know to start `Julia` in various modes (command line prompt, `IJulia`), how to exit, learn some features and be able to write simple programs.

## Credits

This notebook is based on the [slides](https://github.com/JuliaLang/julia-tutorial/tree/master/LightningRound) accompanying  the Lightning Round [video]( https://www.youtube.com/watch?v=37L1OMk_3FU&feature=player_embedded#at=33) by [Alan Edelman](http://www-math.mit.edu/~edelman/index.php), all part of the [Julia Tutorial](https://github.com/JuliaLang/julia-tutorial).

## Julia resources

Julia resources are accessible through the [Julia home page](http://julialang.org).

Please check `packages`, `docs` and `juliacon` (_here you will also find links to videos from previous conferences_).

## Execution
To execute cell use `Shift + Enter` or press `Play` (__Run cell__).

To run all cells in the notebook go to `Cell` -> `Run All` 

## Markdown cells

Possibility to write comments / code / formulas in `Markdown` cells, makes Jupyter notebooks ideal for teaching and research. Text is written using _Julia Markdown_, which is _GitHub Markdown_ with additional understanding of basic `LaTeX`.

[Mastering (GitHub) Markdown](https://guides.github.com/features/mastering-markdown/) is a 3-minute read, another short and very good manual is at http://daringfireball.net/projects/markdown/.

Some particulars of Julia Markdown are described in 
[Documentation](https://docs.julialang.org/en/latest/manual/documentation/) section of Julia Manual, yet another short read.

## `nbconvert`

It is extremely easy to convert notebooks to slides, LaTeX, or PDF.
For details see the 
[documentation](https://nbconvert.readthedocs.org/en/latest/usage.html).

### Slides

Clicking `View` -> `Cell Toolbar` -> `Slideshow` opens the `Slide Type` menu for each cell.

The slideshow is made with the command

`jupyter nbconvert --to slides notebook.ipynb`

The slideshow is displayed in browser with the command

`jupyter nbconvert --to slides --post serve notebook.ipynb`


### LaTeX

`jupyter nbconvert --to latex notebook.ipynb`

###  PDF 

`jupyter nbconvert --to PDF notebook.ipynb`

N.B. For the above conversions [Pandoc](http://pandoc.org/installing.html) needs to be installed.

## Which version of `Julia` is running?

In [1]:
versioninfo()

Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)
Environment:
  JULIABOX = true
  JULIA_PKG_SERVER = https://pkg.juliacomputing.com
  JULIA = /opt/julia-0.6/bin/julia
  JULIA_KERNELS = ['julia-0.5', 'julia-0.6', 'julia-1.0']
  JULIABOX_ROLE = 


## Quitting

__Exiting__ from `julia>` or __restarting kernel__ in `IJulia`

In [2]:
# exit()

## Documentation

Documentation is well written and the starting point is http://docs.julialang.org/en/latest/

But, also remeber that `Julia` is __open source__ and all routines are available on [GitHub](http://github.com). You will learn how to make full use of this later in the course.

## Punctuation review

* `[...]` are for indexing, array constructors and __Comprehensions__
* `(...)` are __required__ for functions `quit()`, `tic()`, `toc()`, `help()` 
* `{...}` are for arrays
* `#` is for comments

## Basic indexing

In [3]:
A=rand(5,5) # Matrix with random entries between 0 and 1

5×5 Array{Float64,2}:
 0.736037  0.309023  0.845494   0.99521   0.66354 
 0.203446  0.602611  0.708334   0.547989  0.272523
 0.882626  0.561093  0.0539961  0.643632  0.680406
 0.71522   0.427387  0.363908   0.560041  0.742567
 0.343671  0.281507  0.219999   0.6633    0.58327 

In [4]:
A[1,1]

0.7360370333414579

In [5]:
rand(5,5)[1:2,3:4] # You can even do this

2×2 Array{Float64,2}:
 0.890409  0.10505 
 0.276847  0.724884

### Indexing is elegant

If you want to compute the lower right $2\times 2$ block of $A^{10}$, in most languages you need to first compute $B=A^{10}$ and then index into $B$. In Julia, the command is simply

In [6]:
(A^10)[4:5,4:5] # Parenthesses around A^10 are necessary

2×2 Array{Float64,2}:
 6094.02  5393.35
 4409.96  3902.92

### Comprehensions - elegant array constructors

In [7]:
[i for i=1:5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [8]:
x=1:10

1:10

In [9]:
[ x[i]+x[i+1] for i=1:9 ]

9-element Array{Int64,1}:
  3
  5
  7
  9
 11
 13
 15
 17
 19

In [10]:
using LinearAlgebra

In [11]:
z = [Matrix{Int16}(I,n,n) for n=1:5]  # z is Array of Arrays

5-element Array{Array{Int16,2},1}:
 [1]                                             
 [1 0; 0 1]                                      
 [1 0 0; 0 1 0; 0 0 1]                           
 [1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 1]            
 [1 0 … 0 0; 0 1 … 0 0; … ; 0 0 … 1 0; 0 0 … 0 1]

In [12]:
z[1] # First element is a 1x1 Array

1×1 Array{Int16,2}:
 1

In [13]:
z[4] # What is the fourth element?

4×4 Array{Int16,2}:
 1  0  0  0
 0  1  0  0
 0  0  1  0
 0  0  0  1

In [14]:
A=[ i+j for i=1:5, j=1:5 ] # Another example of a comprehension

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [15]:
B=[ i+j for i=1:5, j=1.0:5 ] # Notice the promotion

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

## Commands `ndims()` and `typeof()`

In [16]:
ndims(B)

2

In [17]:
ndims(z) # z is a one-dimensional array

1

In [18]:
typeof(z) # Array of Arrays

Array{Array{Int16,2},1}

In [19]:
typeof(z[5]) # z[5] is a two-dimensional array

Array{Int16,2}

In [20]:
typeof(A)

Array{Int64,2}

## Vectors are 1-dimensional arrays

See [Multi-dimensional arrays](https://docs.julialang.org/en/latest/manual/arrays/#man-multi-dim-arrays-1) for more.

In [21]:
v=rand(5,1) # This is 2-dimensional array

5×1 Array{Float64,2}:
 0.8576758492795096  
 0.42408366961655775 
 0.7833775485046635  
 0.9934197824660047  
 0.051337796727130236

In [22]:
vv=vec(v) # This is an 1-dimensional array or vector

5-element Array{Float64,1}:
 0.8576758492795096  
 0.42408366961655775 
 0.7833775485046635  
 0.9934197824660047  
 0.051337796727130236

In [23]:
v==vv  # Notice that they are different

false

In [24]:
v-vv # Again a promotion

5×1 Array{Float64,2}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [25]:
w=rand(5) # This is again a vector

5-element Array{Float64,1}:
 0.8104843287388916 
 0.23987286683061337
 0.34526378065399066
 0.9110452098757666 
 0.5150428544291614 

In [26]:
Mv=[v w] # First column is a 5 x 1 matrix, second column is a vector of length 5

5×2 Array{Float64,2}:
 0.857676   0.810484
 0.424084   0.239873
 0.783378   0.345264
 0.99342    0.911045
 0.0513378  0.515043

In [27]:
x=Mv[:,1] # Matrix columns are extracted as vectors

5-element Array{Float64,1}:
 0.8576758492795096  
 0.42408366961655775 
 0.7833775485046635  
 0.9934197824660047  
 0.051337796727130236

In [28]:
y=Mv[:,2]

5-element Array{Float64,1}:
 0.8104843287388916 
 0.23987286683061337
 0.34526378065399066
 0.9110452098757666 
 0.5150428544291614 

In [29]:
x==v # The types differ

false

In [30]:
y==w

true

In [31]:
Mv[1,:] # matrix rows are also vectors

2-element Array{Float64,1}:
 0.8576758492795096
 0.8104843287388916

### 1D and 2D arrays

In [32]:
w=1.0:5

1.0:1.0:5.0

In [33]:
A*w

5-element Array{Float64,1}:
  70.0
  85.0
 100.0
 115.0
 130.0

In [34]:
w=collect(1.0:5) 

5-element Array{Float64,1}:
 1.0
 2.0
 3.0
 4.0
 5.0

In [35]:
A*w  # This returns a 1-dimensional array

5-element Array{Float64,1}:
  70.0
  85.0
 100.0
 115.0
 130.0

In [36]:
A*v # This returns a 2-dimensional array - v is a 5 x 1 array

5×1 Array{Float64,2}:
 11.396238594120149
 14.506133240714016
 17.616027887307883
 20.725922533901745
 23.835817180495617

## Discussion

Such behavior is due to the fact that `Julia` has vectors as a special type. __ Pros? Cons? __
 
What is matrix $\times$ vector?

What is the result of 

$$ C[i,j]=A[i,:]*B[:,j]$$

In [40]:
B=[A[i,:]⋅A[:,j] for i=1:5, j=1:5] # use ⋅

5×5 Array{Int64,2}:
  90  110  130  150  170
 110  135  160  185  210
 130  160  190  220  250
 150  185  220  255  290
 170  210  250  290  330

## `ones()`, `eye()` and `zeros()`
   
Notice that the output type depends on the argument. This is a general Julia feature called `Multiple dispatch` 
and will be explained later in more detail. 

In [41]:
ones(3,5)

3×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [42]:
ones(Int,5)

5-element Array{Int64,1}:
 1
 1
 1
 1
 1

In [43]:
ones(size(rand(1:3,4,6)))
# The output type depends on the argument. Float64 is the default.

4×6 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0

In [44]:
zeros(3,5)

3×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [45]:
# There is no function eye()
Matrix{Int}(I,4,4)

4×4 Array{Int64,2}:
 1  0  0  0
 0  1  0  0
 0  0  1  0
 0  0  0  1

In [46]:
# I is computed automatically
A=rand(-9:9,4,4)

4×4 Array{Int64,2}:
 2   6   0   3
 3   8   2   4
 6  -6  -3  -1
 4   8  -8   2

In [47]:
A-I

4×4 Array{Int64,2}:
 1   6   0   3
 3   7   2   4
 6  -6  -4  -1
 4   8  -8   1

## Complex numbers

`i` is too valuable symbol for loops, so Julia uses `im` for the complex unit. 

In [48]:
im

im

In [49]:
2im

0 + 2im

In [50]:
typeof(ans)

Complex{Int64}

In [51]:
typeof(2.0im)

Complex{Float64}

In [52]:
complex(3,4) # Another way of defining complex numbers

3 + 4im

In [53]:
complex(3,4.0) # If one of the arguments if Float64, so is the entire number - promotion!

3.0 + 4.0im

In [54]:
sqrt(-1) # This produces an error (like in any other language)

DomainError: DomainError with -1.0:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).

In [55]:
sqrt(complex(-1))  # and this is fine.

0.0 + 1.0im

## Ternary operator
Let us define our version of the sign function

In [56]:
si(x) = (x>0) ? 1 : -1

si (generic function with 1 method)

In [57]:
si(-13)

-1

This is equivalent to:

In [58]:
function si(x)
    if x>0
        return 1
    else
        return -1
    end
end

si (generic function with 1 method)

In [59]:
si(pi-8), si(0), si(0.0)

(-1, -1, -1)

The expressions can be nested:

In [63]:
si(x) = (x>0) ? 1 : ((x<0) ? -1 : 0) # now si(0) is 0

si (generic function with 1 method)

In [64]:
si(π-8), si(0) # '\pi Tab' produces π and means π

(-1, 0)

## Typing
Special mathematical (LaTeX) symbols can be used (like $\alpha$, $\Xi$, $\pi$, $\oplus$, $\cdot$, etc.). The symbol in both, the notebook and command line version, is produced by writing 
LaTeX command followed by `Tab` 

In [65]:
Ξ = 8; Ψ  = 6; Γ = Ξ ⋅ Ψ


48

In [66]:
typeof(Γ)

Int64

## Writing a program and running a file

Special feature of Julia is that the results of commands are not displayed, unless explicitely required. 

To display results you can use commands `@show` or `println()` (or many others, see the [Text I/O](http://julia.readthedocs.org/en/latest/stdlib/base/?highlight=print#text-i-o) in the manual.)

Consider the file `deploy.jl` with the following code
```julia
n=int(ARGS[1])          # take one integer argument
println(rand(1:n,n,n))  # generate and print n x n matrix of random integers between 1 and n
@show b=3               # set b to 3 and show the result
c=4                     # set c to 4
```
Running the program in the shell gives
```julia
$ julia deploy.jl 5
[1 3 2 4 1
 5 3 1 1 4
 5 4 2 2 5
 3 1 2 3 4
 4 4 5 4 4]
b = 3 => 3
```
Notice that the result of the last command (_c_) is not displayed.

>You can, of course, also run the above command in the `Console` tab of `JuliaBox`. To do this, you first have to change the directory
```
cd Julia-Course/src
```

Similarly, the program can be converted to executable and run directly, 
without referencing `julia` in the command line.
The refernece to `julia` must be added in the first line, as in the file `deploy1.jl`:
```julia
#!/usr/bin/julia
n=int(ARGS[1])
println(rand(1:n,n,n))
@show b=3
c=4
```
In the shell do:
```
$ chmod +x deploy1.jl
$ ./deploy1.jl 5
[4 5 3 2 5
 4 2 1 5 1
 3 2 4 5 1
 2 4 4 3 1
 3 4 5 3 3]
b = 3 => 3
```
Finally, to run the same program in `julia` shell or `IJulia`, the input has to be changed, as in the file `deploy2.jl`:
```julia
n=int(readline())
println(rand(1:n,n,n))
@show b=3
c=4
```
__Notice that now the result of the last line is displayed by default__  - in this case it is `4`, the values of `c`. The output of the random matrix and of `b` is forced.

In [67]:
include("deploy2.jl")

stdin> 3
[1 2 3; 1 2 1; 3 3 3]
b = 3 = 3


4

In [68]:
?readline()

```
readline(io::IO=stdin; keep::Bool=false)
readline(filename::AbstractString; keep::Bool=false)
```

Read a single line of text from the given I/O stream or file (defaults to `stdin`). When reading from a file, the text is assumed to be encoded in UTF-8. Lines in the input end with `'\n'` or `"\r\n"` or the end of an input stream. When `keep` is false (as it is by default), these trailing newline characters are removed from the line before it is returned. When `keep` is true, they are returned as part of the line.

# Examples

```jldoctest
julia> open("my_file.txt", "w") do io
           write(io, "JuliaLang is a GitHub organization.\nIt has many members.\n");
       end
57

julia> readline("my_file.txt")
"JuliaLang is a GitHub organization."

julia> readline("my_file.txt", keep=true)
"JuliaLang is a GitHub organization.\n"

julia> rm("my_file.txt")
```


## Running external programs and unix pipe

### `run()` - calling external program

In [69]:
?run

search: run trunc truncate round rounding RoundUp RoundDown RoundToZero



```
run(command, args...; wait::Bool = true)
```

Run a command object, constructed with backticks. Throws an error if anything goes wrong, including the process exiting with a non-zero status (when `wait` is true).

If `wait` is false, the process runs asynchronously. You can later wait for it and check its exit status by calling `success` on the returned process object.

When `wait` is false, the process' I/O streams are directed to `devnull`. When `wait` is true, I/O streams are shared with the parent process. Use [`pipeline`](@ref) to control I/O redirection.


Notice, that this is not a gret help, Julia has much better commands for this.

In [70]:
# This calls the unix Calendar program
run(`cal`)

   November 2018      
Su Mo Tu We Th Fr Sa  
             1  2  3  
 4  5  6  7  8  9 10  
11 _1_2 13 14 15 16 17  
18 19 20 21 22 23 24  
25 26 27 28 29 30     
                      


Process(`cal`, ProcessExited(0))

In [71]:
# The pipe is '|>' instead of usual '|'
run(pipeline(`cal`,`grep Sa`)) 

Su Mo Tu We Th Fr Sa  


Base.ProcessChain(Base.Process[Process(`cal`, ProcessExited(0)), Process(`grep Sa`, ProcessExited(0))], RawFD(0x00000000), RawFD(0x00000001), RawFD(0x00000002))

### `ccall()` - calling `C` program

In [72]:
?ccall

search: ccall AbstractChannel



```
ccall((function_name, library), returntype, (argtype1, ...), argvalue1, ...)
ccall(function_pointer, returntype, (argtype1, ...), argvalue1, ...)
```

Call a function in a C-exported shared library, specified by the tuple `(function_name, library)`, where each component is either a string or symbol. Alternatively, `ccall` may also be used to call a function pointer `function_pointer`, such as one returned by `dlsym`.

Note that the argument type tuple must be a literal tuple, and not a tuple-valued variable or expression.

Each `argvalue` to the `ccall` will be converted to the corresponding `argtype`, by automatic insertion of calls to `unsafe_convert(argtype, cconvert(argtype, argvalue))`. (See also the documentation for [`unsafe_convert`](@ref Base.unsafe_convert) and [`cconvert`](@ref Base.cconvert) for further details.) In most cases, this simply results in a call to `convert(argtype, argvalue)`.


In [73]:
# Simple version
ccall(:clock,Int,()) 

35446132

In [81]:
path = ccall((:getenv, "libc.so.6"), Cstring, (Cstring,), "SHELL")

Cstring(0x00007ffcb94df86a)

In [82]:
unsafe_string(path) # Human readable version

"/bin/bash"

## `Task()` and `Channel`
`Julia` has  a control flow feature that allows computations to be suspended 
and resumed in a flexible manner (see
[Tasks](https://docs.julialang.org/en/latest/manual/control-flow/#man-tasks-1) in the manual).

In [83]:
function stepbystep(c::Channel)
    put!(c, "start")
    for n=1:3
        put!(c,n^2)    
    end
    put!(c,"stop")
end

stepbystep (generic function with 1 method)

In [84]:
c1=Channel(stepbystep)

Channel{Any}(sz_max:0,sz_curr:1)

In [85]:
take!(c1)

"start"

In [86]:
take!(c1)

1

In [87]:
take!(c1)

4

In [88]:
take!(c1)

9

In [89]:
take!(c1)

"stop"

In [90]:
take!(c1) # Guess what comes next?

InvalidStateException: InvalidStateException("Channel is closed.", :closed)